### Public API Request to get all picture with images.
GET https://collectionapi.metmuseum.org//public/collection/v1/search?hasImages=true&title=true&q=any

### Get all pictures with public images.
GET http://localhost:3000/pictures

### Public API Request to get an object by id.
GET https://collectionapi.metmuseum.org//public/collection/v1/objects/205116

### Get suspected object with no images.
GET https://collectionapi.metmuseum.org//public/collection/v1/objects/478572

### Get render card for working object id.
GET http://localhost:3000/render/205116

### Get render card for not working object id.
GET http://localhost:3000/render/478572